export const GET_NOW_PLAYING_FILM_SUCCESS =  'GET_NOWPLAYING_FILM_SUCCESS';
export const GET_NOW_COMMING_FILM_SUCCESS = 'GET_NOW_COMMING_FILM_SUCCESS';
export const GET_FILM_DETAIL = 'GET_FILM_DETAIL';
export const SHOW_LEFT_NAV = 'SHOW_LEFT_NAV';
export const SHOW_LOADING = 'SHOW_LOADING';